require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe SlideshowsController do

  def mock_slideshow(stubs={})
    @mock_slideshow ||= mock_model(Slideshow, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all slideshows as @slideshows" do
      Slideshow.stub(:all) { [mock_slideshow] }
      get :index
      assigns(:slideshows).should eq([mock_slideshow])
    end
  end

  describe "GET show" do
    it "assigns the requested slideshow as @slideshow" do
      Slideshow.stub(:find).with("37") { mock_slideshow }
      get :show, :id => "37"
      assigns(:slideshow).should be(mock_slideshow)
    end
  end

  describe "GET new" do
    it "assigns a new slideshow as @slideshow" do
      Slideshow.stub(:new) { mock_slideshow }
      get :new
      assigns(:slideshow).should be(mock_slideshow)
    end
  end

  describe "GET edit" do
    it "assigns the requested slideshow as @slideshow" do
      Slideshow.stub(:find).with("37") { mock_slideshow }
      get :edit, :id => "37"
      assigns(:slideshow).should be(mock_slideshow)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created slideshow as @slideshow" do
        Slideshow.stub(:new).with({'these' => 'params'}) { mock_slideshow(:save => true) }
        post :create, :slideshow => {'these' => 'params'}
        assigns(:slideshow).should be(mock_slideshow)
      end

      it "redirects to the created slideshow" do
        Slideshow.stub(:new) { mock_slideshow(:save => true) }
        post :create, :slideshow => {}
        response.should redirect_to(slideshow_url(mock_slideshow))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved slideshow as @slideshow" do
        Slideshow.stub(:new).with({'these' => 'params'}) { mock_slideshow(:save => false) }
        post :create, :slideshow => {'these' => 'params'}
        assigns(:slideshow).should be(mock_slideshow)
      end

      it "re-renders the 'new' template" do
        Slideshow.stub(:new) { mock_slideshow(:save => false) }
        post :create, :slideshow => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested slideshow" do
        Slideshow.stub(:find).with("37") { mock_slideshow }
        mock_slideshow.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :slideshow => {'these' => 'params'}
      end

      it "assigns the requested slideshow as @slideshow" do
        Slideshow.stub(:find) { mock_slideshow(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:slideshow).should be(mock_slideshow)
      end

      it "redirects to the slideshow" do
        Slideshow.stub(:find) { mock_slideshow(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(slideshow_url(mock_slideshow))
      end
    end

    describe "with invalid params" do
      it "assigns the slideshow as @slideshow" do
        Slideshow.stub(:find) { mock_slideshow(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:slideshow).should be(mock_slideshow)
      end

      it "re-renders the 'edit' template" do
        Slideshow.stub(:find) { mock_slideshow(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested slideshow" do
      Slideshow.stub(:find).with("37") { mock_slideshow }
      mock_slideshow.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the slideshows list" do
      Slideshow.stub(:find) { mock_slideshow }
      delete :destroy, :id => "1"
      response.should redirect_to(slideshows_url)
    end
  end

end
