require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe SlidesController do

  def mock_slide(stubs={})
    @mock_slide ||= mock_model(Slide, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all slides as @slides" do
      Slide.stub(:all) { [mock_slide] }
      get :index
      assigns(:slides).should eq([mock_slide])
    end
  end

  describe "GET show" do
    it "assigns the requested slide as @slide" do
      Slide.stub(:find).with("37") { mock_slide }
      get :show, :id => "37"
      assigns(:slide).should be(mock_slide)
    end
  end

  describe "GET new" do
    it "assigns a new slide as @slide" do
      Slide.stub(:new) { mock_slide }
      get :new
      assigns(:slide).should be(mock_slide)
    end
  end

  describe "GET edit" do
    it "assigns the requested slide as @slide" do
      Slide.stub(:find).with("37") { mock_slide }
      get :edit, :id => "37"
      assigns(:slide).should be(mock_slide)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created slide as @slide" do
        Slide.stub(:new).with({'these' => 'params'}) { mock_slide(:save => true) }
        post :create, :slide => {'these' => 'params'}
        assigns(:slide).should be(mock_slide)
      end

      it "redirects to the created slide" do
        Slide.stub(:new) { mock_slide(:save => true) }
        post :create, :slide => {}
        response.should redirect_to(slide_url(mock_slide))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved slide as @slide" do
        Slide.stub(:new).with({'these' => 'params'}) { mock_slide(:save => false) }
        post :create, :slide => {'these' => 'params'}
        assigns(:slide).should be(mock_slide)
      end

      it "re-renders the 'new' template" do
        Slide.stub(:new) { mock_slide(:save => false) }
        post :create, :slide => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested slide" do
        Slide.stub(:find).with("37") { mock_slide }
        mock_slide.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :slide => {'these' => 'params'}
      end

      it "assigns the requested slide as @slide" do
        Slide.stub(:find) { mock_slide(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:slide).should be(mock_slide)
      end

      it "redirects to the slide" do
        Slide.stub(:find) { mock_slide(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(slide_url(mock_slide))
      end
    end

    describe "with invalid params" do
      it "assigns the slide as @slide" do
        Slide.stub(:find) { mock_slide(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:slide).should be(mock_slide)
      end

      it "re-renders the 'edit' template" do
        Slide.stub(:find) { mock_slide(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested slide" do
      Slide.stub(:find).with("37") { mock_slide }
      mock_slide.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the slides list" do
      Slide.stub(:find) { mock_slide }
      delete :destroy, :id => "1"
      response.should redirect_to(slides_url)
    end
  end

end
